# Generated by Django 4.2 on 2023-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_textmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
